export default {
    // 登陆
    LOGIN: "/auth/login",
    // 注册
    REGISTER: "/auth/register",
    // 登出
    LOGOUT: "/auth/logout",
    // 获取用户信息
    GET_USER_INFO: "/userInfo",
    // 更新用户信息
    UPDATE_USER_INFO: "/userInfo/update",
    // 上传用户头像
    UPLOAD_AVATAR: "/avatar/upload",
    // 更新用户头像
    CHANGE_AVATAR: "/avatar/change",
    // 创建笔记
    NEW_NOTE: "/note",
    // 删除笔记
    DEL_NOTE: "/note",
    // 获取笔记列表
    NOTE_LIST: "/note/list",
    // 获取我的笔记
    MY_NOTE_LIST: "/note/myNotes",
    // 获取笔记图片
    NOTE_PIC: "/note/pic",
    // 点赞
    LIKE_NOTE: "/note/like",
    // 取消点赞
    DISLIKE_NOTE: "/note/dislike",
    // 收藏笔记
    COLLECT_NOTE: "/note/collect",
    // 取消收藏笔记
    CANCEL_COLLECT_NOTE: "/note/cancelCollect",
}